In [1]:
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.gaussian_process.kernels import RBF
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.decomposition import PCA
from sklearn import preprocessing
import matplotlib.pyplot as plt
from pandas import get_dummies
from sklearn import datasets
from sklearn.svm import SVC
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib
import warnings
import sklearn
import scipy
import numpy
import json
import sys
import csv
import os

In [2]:
print('matplotlib: {}'.format(matplotlib.__version__))
print('sklearn: {}'.format(sklearn.__version__))
print('scipy: {}'.format(scipy.__version__))
print('seaborn: {}'.format(sns.__version__))
print('pandas: {}'.format(pd.__version__))
print('numpy: {}'.format(np.__version__))
print('Python: {}'.format(sys.version))

matplotlib: 3.0.2
sklearn: 0.20.1
scipy: 1.1.0
seaborn: 0.9.0
pandas: 0.23.4
numpy: 1.15.4
Python: 3.7.1 (default, Dec 14 2018, 19:28:38) 
[GCC 7.3.0]


In [3]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [4]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [5]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [6]:
m.shape

(2, 3)

In [7]:
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [8]:
n.reshape(5, 3)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [9]:
o = np.linspace(0,4,9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [10]:
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.diag((y))

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [15]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [16]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

# 2-2 Numpy:Combining Arrays

In [17]:
p = np.ones([2,3],int) 
p

array([[1, 1, 1],
       [1, 1, 1]])

In [18]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [19]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

## Numpy:Operations¶

In [20]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [21]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


In [22]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


In [23]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [24]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [25]:
len(z)

2

In [26]:
z.shape

(2, 3)

In [27]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [28]:
z.T.shape

(3, 2)

In [29]:
z.dtype

dtype('int64')

In [30]:
type(z)

numpy.ndarray

In [31]:
z = z.astype('f')
z

array([[ 4.,  5.,  6.],
       [16., 25., 36.]], dtype=float32)

In [32]:
z.dtype

dtype('float32')

#  Numpy: Math Functions

In [141]:
a = np.array([-4, -2, 1, 3, 5])

In [144]:
a.sum()              of a slice

3

In [35]:
a.max()

5

In [36]:
a.min()

-4

In [37]:
a.mean()

0.6

In [38]:
a.std()

3.2619012860600183

In [39]:
b = [-1,2,3]
b

[-1, 2, 3]

In [40]:
[abs(x) for x in b]

[1, 2, 3]

In [41]:
a.argmax()

4

In [42]:
a.argmin()

0

## Numpy:Indexing / Slicing

In [43]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [44]:
s[0], s[4], s[-1]

(0, 16, 144)

In [45]:
s[1:5]

array([ 1,  4,  9, 16])

In [46]:
s[-4:]

array([ 81, 100, 121, 144])

In [47]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [48]:
s[-5::2]

array([ 64, 100, 144])

In [49]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [50]:
r[2, 2]

14

In [51]:
r[3, 3:6]

array([21, 22, 23])

In [52]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [53]:
r[-1, ::2]

array([30, 32, 34])

In [54]:
r[:, ::4]

array([[ 0,  4],
       [ 6, 10],
       [12, 16],
       [18, 22],
       [24, 28],
       [30, 34]])

In [55]:
r[r > 30]

array([31, 32, 33, 34, 35])

In [56]:
r[r % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34])

In [57]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [58]:
r[r % 2 != 0] = 0
r

array([[ 0,  0,  2,  0,  4,  0],
       [ 6,  0,  8,  0, 10,  0],
       [12,  0, 14,  0, 16,  0],
       [18,  0, 20,  0, 22,  0],
       [24,  0, 26,  0, 28,  0],
       [30, 30, 30, 30, 30, 30]])

##  Numpy :Copying Data¶

In [59]:
r2 = r[:3,:3]
r2

array([[ 0,  0,  2],
       [ 6,  0,  8],
       [12,  0, 14]])

In [60]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [61]:
r          #r` has also been changed!

array([[ 0,  0,  0,  0,  4,  0],
       [ 0,  0,  0,  0, 10,  0],
       [ 0,  0,  0,  0, 16,  0],
       [18,  0, 20,  0, 22,  0],
       [24,  0, 26,  0, 28,  0],
       [30, 30, 30, 30, 30, 30]])

In [62]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  0,  4,  0],
       [ 0,  0,  0,  0, 10,  0],
       [ 0,  0,  0,  0, 16,  0],
       [18,  0, 20,  0, 22,  0],
       [24,  0, 26,  0, 28,  0],
       [30, 30, 30, 30, 30, 30]])

In [63]:
r_copy = r[:]
r_copy

array([[ 0,  0,  0,  0,  4,  0],
       [ 0,  0,  0,  0, 10,  0],
       [ 0,  0,  0,  0, 16,  0],
       [18,  0, 20,  0, 22,  0],
       [24,  0, 26,  0, 28,  0],
       [30, 30, 30, 30, 30, 30]])

In [64]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


# Numpy: Iterating Over Arrays¶

In [65]:
test = np.random.randint(0,10,(4,3))
test

array([[4, 0, 3],
       [6, 7, 2],
       [2, 8, 4],
       [9, 3, 5]])

In [66]:
for row in test:
    print(row)

[4 0 3]
[6 7 2]
[2 8 4]
[9 3 5]


In [67]:
for i in range(len(test)):
    print(test[i])

[4 0 3]
[6 7 2]
[2 8 4]
[9 3 5]


In [68]:
for i, row in enumerate(test):      #Iterate by row and index:
    print('row', i, 'is', row)

row 0 is [4 0 3]
row 1 is [6 7 2]
row 2 is [2 8 4]
row 3 is [9 3 5]


In [69]:
test2 = test**2
test2

array([[16,  0,  9],
       [36, 49,  4],
       [ 4, 64, 16],
       [81,  9, 25]])

In [70]:
for i, j in zip(test, test2):   # Use `zip` to iterate over multiple iterables.
    print(i,'+',j,'=',i+j)

[4 0 3] + [16  0  9] = [20  0 12]
[6 7 2] + [36 49  4] = [42 56  6]
[2 8 4] + [ 4 64 16] = [ 6 72 20]
[9 3 5] + [81  9 25] = [90 12 30]


## Numpy: The Series Data Structure¶

In [71]:
animals = ['Tiger', 'Bear', 'Moose']
pd.Series(animals)

0    Tiger
1     Bear
2    Moose
dtype: object

In [72]:
numbers = [1, 2, 3]
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

In [73]:
numbers = [1, 2, None]
pd.Series(numbers)

0    1.0
1    2.0
2    NaN
dtype: float64

In [74]:
np.nan == None

False

In [75]:
np.isnan(np.nan)

True

In [76]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [77]:
s.index

Index(['Archery', 'Golf', 'Sumo', 'Taekwondo'], dtype='object')

In [78]:
s = pd.Series(['Tiger', 'Bear', 'Moose'], index=['India', 'America', 'Canada'])
s

India      Tiger
America     Bear
Canada     Moose
dtype: object

In [79]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports, index=['Golf', 'Sumo', 'Hockey'])
s

Golf      Scotland
Sumo         Japan
Hockey         NaN
dtype: object

#  Numpy: Querying a Series

In [80]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [81]:
s.iloc[3]

'South Korea'

In [82]:
s.loc['Taekwondo']

'South Korea'

In [83]:
s[3]

'South Korea'

In [84]:
s['Taekwondo']

'South Korea'

In [85]:
sports = {99: 'Bhutan',
          100: 'Scotland',
          101: 'Japan',
          102: 'South Korea'}
s = pd.Series(sports)
s

99          Bhutan
100       Scotland
101          Japan
102    South Korea
dtype: object

In [86]:
s.iloc[2]                   # Q why is s[2] not locking

'Japan'

In [87]:
s.loc[100]

'Scotland'

In [88]:
s[100]

'Scotland'

In [89]:
s = pd.Series([100.00, 120.00, 101.00, 3.00])
s

0    100.0
1    120.0
2    101.0
3      3.0
dtype: float64

In [90]:
total = 0
for item in s:
    total += item
print(total)    

324.0


In [91]:
total = np.sum(s)
print(total)

324.0


In [92]:
m=np.random.randint(0,1000,10000)

In [93]:
s=pd.Series(np.random.randint(0,1000,10000))
s.head()

0    925
1    129
2     10
3    366
4    707
dtype: int64

In [94]:
len(s)

10000

In [95]:
%%timeit -n 100
summary = 0
for item in s:
    summary+=item

1.17 ms ± 25.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [96]:
%%timeit -n 100
summary = np.sum(s)

227 µs ± 58.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [97]:
s += 2
s.head()

0    927
1    131
2     12
3    368
4    709
dtype: int64

In [98]:
for label, value in s.iteritems():
    s.set_value(label, value+2)
s.head()

/home/kadas/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  


0    929
1    133
2     14
3    370
4    711
dtype: int64

In [99]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,100))
for label, value in s.iteritems():
    s.loc[label]= value+2

16.1 ms ± 1.47 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [100]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,100))
s+=2

336 µs ± 65.4 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [101]:
%%timeit -n 100
q = pd.Series(np.random.randint(0,1000,10000))
total = 0
for item in q:
    total += item 


1.26 ms ± 15.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [102]:
s = pd.Series([1, 2, 3])
s.loc['Animals'] = 'bears'
s

0              1
1              2
2              3
Animals    bears
dtype: object

In [103]:
original_sports = pd.Series({'Archery': 'Bhutan',
                   'Golf': 'Scotland',
                   'Sumo': 'Japan',
                   'Taekwondo': 'South Korea'})
cricket_loving_countries = pd.Series(['Australia',
                                      'Barbados',
                                      'Pakistan',
                                      'England'],
                                   index=['Cricket',
                                          'Cricket',
                                          'Cricket',
                                          'Cricket'])
all_countries = original_sports.append(cricket_loving_countries)


In [104]:
original_sports

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [105]:
cricket_loving_countries

Cricket    Australia
Cricket     Barbados
Cricket     Pakistan
Cricket      England
dtype: object

In [106]:
all_countries

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
Cricket        Australia
Cricket         Barbados
Cricket         Pakistan
Cricket          England
dtype: object

In [107]:
all_countries.loc['Cricket']

Cricket    Australia
Cricket     Barbados
Cricket     Pakistan
Cricket      England
dtype: object

In [108]:
all_countries['Cricket']

Cricket    Australia
Cricket     Barbados
Cricket     Pakistan
Cricket      England
dtype: object

# Numphy Distributions

In [109]:
np.random.binomial(10,0.5)

3

In [133]:
np.random.binomial(1,0.5)

1

In [111]:
np.random.binomial(10,0.5)/10

0.5

In [112]:
np.random.binomial(1000, 0.5)/1000

0.497

In [113]:
chance_of_tornado = 0.01/100
np.random.binomial(100000, chance_of_tornado)

18

In [114]:
chance_of_tornado = 0.01

tornado_events = np.random.binomial(1, chance_of_tornado, 1000000)
tornado_events

array([0, 0, 0, ..., 0, 0, 0])

In [137]:
len(tornado_events)

1000000

In [136]:
np.random.binomial(1,0.01)

0

In [116]:
chance_of_tornado = 0.01

tornado_events = np.random.binomial(1, chance_of_tornado,1000000)

two_days_in_a_row = 0
for j in range(1, len(tornado_events)-1):
    if tornado_events[j] == 1 and tornado_events[j-1] == 1:
        two_days_in_a_row +=1
print('{} tornadoes back to back in {} years'.format(two_days_in_a_row,1000000/365))

94 tornadoes back to back in 2739.72602739726 years


In [117]:
np.random.uniform(0, 1)

0.8084122022862981

In [118]:
np.random.normal(0.75)                 #what if we have both 

2.069841592117453

In [139]:
distribution = np.random.normal(0.75,size=1000)
distribution

array([ 1.64023056e+00,  1.66131286e+00,  1.10871044e+00,  4.46254069e-01,
        3.19959799e+00,  5.51631259e-01,  6.02548683e-01,  1.70988130e+00,
        2.96318992e-01,  5.40833826e-01,  7.58793325e-01, -1.10148167e+00,
        2.37090154e-01,  2.69716705e-01,  2.54958563e-01,  1.21080230e+00,
        1.71498428e-01,  1.46629972e+00,  1.44203376e-01,  5.45599351e-01,
        2.52528543e+00,  8.03610379e-01, -3.69288499e-02,  1.31136206e-01,
       -7.68476727e-02,  5.37309864e-01, -1.69536738e-01,  3.69007039e-01,
        1.36129218e+00,  2.36174226e-01,  1.83012738e+00, -3.31312802e-01,
        1.26505654e+00,  6.50065947e-01,  2.54868640e-02,  1.39226912e-01,
        2.34245560e+00, -6.44659965e-01,  1.61513886e+00,  9.44434332e-01,
        5.88532227e-01,  7.11293953e-01,  2.76024100e-01,  1.09962557e+00,
        9.59690500e-01,  1.61191772e+00,  5.08110264e-01, -8.51498722e-01,
        1.57019111e+00,  8.69098526e-01,  7.20650611e-03,  5.97930475e-01,
        2.82860128e+00,  

In [121]:
np.sqrt(np.sum((np.mean(distribution)-distribution)**2)/len(distribution))

0.9571615296127635

In [122]:
np.sqrt(25)

5.0

In [123]:
np.mean(distribution)

0.7040091639082127

In [124]:
np.mean(distribution)-distribution

array([ 0.45411604,  0.85065553,  0.40118064,  0.14400805, -0.31359431,
       -2.16357421, -0.07318583, -0.87809804,  0.478383  ,  0.16913288,
        1.37508669,  0.24929039, -0.29436641, -0.21095384,  0.66552054,
        0.89869889, -0.46366921,  0.98326381,  0.08828102,  1.23295216,
        0.64964495,  1.83750269,  2.1603754 ,  2.44524788,  0.16220015,
        0.45062035,  0.11448654,  0.40204732, -0.20409094,  1.05661907,
        0.52990657,  0.09010651, -0.1885581 ,  0.72008752, -0.81800265,
        0.99080216,  1.81973796, -1.19051111,  0.32049749,  0.70973452,
       -0.90717278,  0.90523511,  0.01889261, -0.13606774, -2.79449863,
       -1.21186699,  2.23403507,  0.86118886,  0.40887822, -1.40416364,
       -1.76310346,  0.52461382, -0.60111909, -0.23082405,  0.64855713,
        0.45552078, -0.12815162, -1.26971656,  1.19113638,  1.31406315,
        2.18660976,  0.82307291,  0.09773941, -1.30879435, -0.52994843,
       -0.2320074 ,  0.38851115,  1.26072769, -1.13638663,  0.31

In [125]:
(np.mean(distribution)-distribution)**2

array([2.06221378e-01, 7.23614835e-01, 1.60945908e-01, 2.07383196e-02,
       9.83413912e-02, 4.68105336e+00, 5.35616591e-03, 7.71056165e-01,
       2.28850296e-01, 2.86059295e-02, 1.89086341e+00, 6.21456967e-02,
       8.66515817e-02, 4.45015214e-02, 4.42917595e-01, 8.07659703e-01,
       2.14989137e-01, 9.66807725e-01, 7.79353927e-03, 1.52017103e+00,
       4.22038561e-01, 3.37641615e+00, 4.66722188e+00, 5.97923720e+00,
       2.63088878e-02, 2.03058699e-01, 1.31071677e-02, 1.61642046e-01,
       4.16531138e-02, 1.11644387e+00, 2.80800976e-01, 8.11918391e-03,
       3.55541568e-02, 5.18526035e-01, 6.69128340e-01, 9.81688922e-01,
       3.31144623e+00, 1.41731671e+00, 1.02718640e-01, 5.03723090e-01,
       8.22962457e-01, 8.19450596e-01, 3.56930641e-04, 1.85144297e-02,
       7.80922257e+00, 1.46862161e+00, 4.99091271e+00, 7.41646254e-01,
       1.67181402e-01, 1.97167554e+00, 3.10853383e+00, 2.75219658e-01,
       3.61344157e-01, 5.32797411e-02, 4.20626357e-01, 2.07499182e-01,
      

In [126]:
np.sum((np.mean(distribution)-distribution)**2)

916.1581937706451

In [127]:
np.sum((np.mean(distribution)-distribution)**2)/len(distribution)

0.9161581937706451

In [128]:
np.sqrt(np.sum((np.mean(distribution)-distribution)**2)/len(distribution))

0.9571615296127635

In [129]:
np.std(distribution)

0.9571615296127635

In [130]:
stats.kurtosis(distribution)

NameError: name 'stats' is not defined